// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package urtyg_ai_agent_if

import (
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/dbif/urtyg_ai_agent_if/ai_chat_logs_if"
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/dbif/urtyg_ai_agent_if/ai_prompt_if"
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/dbif/urtyg_ai_agent_if/ai_session_logs_if"
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/model/dalm/dbm/urtyg_ai_agent/query"
)

type If interface {
	GenQ() *query.Query
	Ai_chat_logs() ai_chat_logs_if.If
	Ai_prompt() ai_prompt_if.If
	Ai_session_logs() ai_session_logs_if.If
}
