// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_knowledge_chunks(db *gorm.DB, opts ...gen.DOOption) ai_knowledge_chunks {
	_ai_knowledge_chunks := ai_knowledge_chunks{}

	_ai_knowledge_chunks.ai_knowledge_chunksDo.UseDB(db, opts...)
	_ai_knowledge_chunks.ai_knowledge_chunksDo.UseModel(&model.Ai_knowledge_chunks{})

	tableName := _ai_knowledge_chunks.ai_knowledge_chunksDo.TableName()
	_ai_knowledge_chunks.ALL = field.NewAsterisk(tableName)
	_ai_knowledge_chunks.ID = field.NewInt64(tableName, "id")
	_ai_knowledge_chunks.KnowledgeDocID = field.NewInt64(tableName, "knowledge_doc_id")
	_ai_knowledge_chunks.ChunkID = field.NewString(tableName, "chunk_id")
	_ai_knowledge_chunks.Content = field.NewString(tableName, "content")
	_ai_knowledge_chunks.Ext = field.NewString(tableName, "ext")
	_ai_knowledge_chunks.Status = field.NewBool(tableName, "status")
	_ai_knowledge_chunks.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_knowledge_chunks.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_knowledge_chunks.fillFieldMap()

	return _ai_knowledge_chunks
}

// ai_knowledge_chunks 知识库文档切片表
type ai_knowledge_chunks struct {
	ai_knowledge_chunksDo ai_knowledge_chunksDo

	ALL            field.Asterisk
	ID             field.Int64
	KnowledgeDocID field.Int64
	ChunkID        field.String
	Content        field.String
	Ext            field.String
	Status         field.Bool
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a ai_knowledge_chunks) Table(newTableName string) *ai_knowledge_chunks {
	a.ai_knowledge_chunksDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_knowledge_chunks) As(alias string) *ai_knowledge_chunks {
	a.ai_knowledge_chunksDo.DO = *(a.ai_knowledge_chunksDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_knowledge_chunks) updateTableName(table string) *ai_knowledge_chunks {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.KnowledgeDocID = field.NewInt64(table, "knowledge_doc_id")
	a.ChunkID = field.NewString(table, "chunk_id")
	a.Content = field.NewString(table, "content")
	a.Ext = field.NewString(table, "ext")
	a.Status = field.NewBool(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_knowledge_chunks) WithContext(ctx context.Context) *ai_knowledge_chunksDo {
	return a.ai_knowledge_chunksDo.WithContext(ctx)
}

func (a ai_knowledge_chunks) TableName() string { return a.ai_knowledge_chunksDo.TableName() }

func (a ai_knowledge_chunks) Alias() string { return a.ai_knowledge_chunksDo.Alias() }

func (a ai_knowledge_chunks) Columns(cols ...field.Expr) gen.Columns {
	return a.ai_knowledge_chunksDo.Columns(cols...)
}

func (a *ai_knowledge_chunks) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_knowledge_chunks) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["knowledge_doc_id"] = a.KnowledgeDocID
	a.fieldMap["chunk_id"] = a.ChunkID
	a.fieldMap["content"] = a.Content
	a.fieldMap["ext"] = a.Ext
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_knowledge_chunks) clone(db *gorm.DB) ai_knowledge_chunks {
	a.ai_knowledge_chunksDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_knowledge_chunks) replaceDB(db *gorm.DB) ai_knowledge_chunks {
	a.ai_knowledge_chunksDo.ReplaceDB(db)
	return a
}

type ai_knowledge_chunksDo struct{ gen.DO }

func (a ai_knowledge_chunksDo) Debug() *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_knowledge_chunksDo) WithContext(ctx context.Context) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_knowledge_chunksDo) ReadDB() *ai_knowledge_chunksDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_knowledge_chunksDo) WriteDB() *ai_knowledge_chunksDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_knowledge_chunksDo) Session(config *gorm.Session) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_knowledge_chunksDo) Clauses(conds ...clause.Expression) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_knowledge_chunksDo) Returning(value interface{}, columns ...string) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_knowledge_chunksDo) Not(conds ...gen.Condition) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_knowledge_chunksDo) Or(conds ...gen.Condition) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_knowledge_chunksDo) Select(conds ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_knowledge_chunksDo) Where(conds ...gen.Condition) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_knowledge_chunksDo) Order(conds ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_knowledge_chunksDo) Distinct(cols ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_knowledge_chunksDo) Omit(cols ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_knowledge_chunksDo) Join(table schema.Tabler, on ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_knowledge_chunksDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_knowledge_chunksDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_knowledge_chunksDo) Group(cols ...field.Expr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_knowledge_chunksDo) Having(conds ...gen.Condition) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_knowledge_chunksDo) Limit(limit int) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_knowledge_chunksDo) Offset(offset int) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_knowledge_chunksDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_knowledge_chunksDo) Unscoped() *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_knowledge_chunksDo) Create(values ...*model.Ai_knowledge_chunks) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_knowledge_chunksDo) CreateInBatches(values []*model.Ai_knowledge_chunks, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_knowledge_chunksDo) Save(values ...*model.Ai_knowledge_chunks) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_knowledge_chunksDo) First() (*model.Ai_knowledge_chunks, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_chunks), nil
	}
}

func (a ai_knowledge_chunksDo) Take() (*model.Ai_knowledge_chunks, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_chunks), nil
	}
}

func (a ai_knowledge_chunksDo) Last() (*model.Ai_knowledge_chunks, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_chunks), nil
	}
}

func (a ai_knowledge_chunksDo) Find() ([]*model.Ai_knowledge_chunks, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_knowledge_chunks), err
}

func (a ai_knowledge_chunksDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_knowledge_chunks, err error) {
	buf := make([]*model.Ai_knowledge_chunks, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_knowledge_chunksDo) FindInBatches(result *[]*model.Ai_knowledge_chunks, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_knowledge_chunksDo) Attrs(attrs ...field.AssignExpr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_knowledge_chunksDo) Assign(attrs ...field.AssignExpr) *ai_knowledge_chunksDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_knowledge_chunksDo) Joins(fields ...field.RelationField) *ai_knowledge_chunksDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_knowledge_chunksDo) Preload(fields ...field.RelationField) *ai_knowledge_chunksDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_knowledge_chunksDo) FirstOrInit() (*model.Ai_knowledge_chunks, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_chunks), nil
	}
}

func (a ai_knowledge_chunksDo) FirstOrCreate() (*model.Ai_knowledge_chunks, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_chunks), nil
	}
}

func (a ai_knowledge_chunksDo) FindByPage(offset int, limit int) (result []*model.Ai_knowledge_chunks, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_knowledge_chunksDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_knowledge_chunksDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_knowledge_chunksDo) Delete(models ...*model.Ai_knowledge_chunks) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_knowledge_chunksDo) withDO(do gen.Dao) *ai_knowledge_chunksDo {
	a.DO = *do.(*gen.DO)
	return a
}
