// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_knowledge_base(db *gorm.DB, opts ...gen.DOOption) ai_knowledge_base {
	_ai_knowledge_base := ai_knowledge_base{}

	_ai_knowledge_base.ai_knowledge_baseDo.UseDB(db, opts...)
	_ai_knowledge_base.ai_knowledge_baseDo.UseModel(&model.Ai_knowledge_base{})

	tableName := _ai_knowledge_base.ai_knowledge_baseDo.TableName()
	_ai_knowledge_base.ALL = field.NewAsterisk(tableName)
	_ai_knowledge_base.ID = field.NewInt64(tableName, "id")
	_ai_knowledge_base.Name = field.NewString(tableName, "name")
	_ai_knowledge_base.Description = field.NewString(tableName, "description")
	_ai_knowledge_base.Category = field.NewString(tableName, "category")
	_ai_knowledge_base.Status = field.NewInt64(tableName, "status")
	_ai_knowledge_base.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_knowledge_base.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_knowledge_base.fillFieldMap()

	return _ai_knowledge_base
}

// ai_knowledge_base 知识库基础表
type ai_knowledge_base struct {
	ai_knowledge_baseDo ai_knowledge_baseDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Description field.String
	Category    field.String
	Status      field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a ai_knowledge_base) Table(newTableName string) *ai_knowledge_base {
	a.ai_knowledge_baseDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_knowledge_base) As(alias string) *ai_knowledge_base {
	a.ai_knowledge_baseDo.DO = *(a.ai_knowledge_baseDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_knowledge_base) updateTableName(table string) *ai_knowledge_base {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")
	a.Category = field.NewString(table, "category")
	a.Status = field.NewInt64(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_knowledge_base) WithContext(ctx context.Context) *ai_knowledge_baseDo {
	return a.ai_knowledge_baseDo.WithContext(ctx)
}

func (a ai_knowledge_base) TableName() string { return a.ai_knowledge_baseDo.TableName() }

func (a ai_knowledge_base) Alias() string { return a.ai_knowledge_baseDo.Alias() }

func (a ai_knowledge_base) Columns(cols ...field.Expr) gen.Columns {
	return a.ai_knowledge_baseDo.Columns(cols...)
}

func (a *ai_knowledge_base) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_knowledge_base) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description
	a.fieldMap["category"] = a.Category
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_knowledge_base) clone(db *gorm.DB) ai_knowledge_base {
	a.ai_knowledge_baseDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_knowledge_base) replaceDB(db *gorm.DB) ai_knowledge_base {
	a.ai_knowledge_baseDo.ReplaceDB(db)
	return a
}

type ai_knowledge_baseDo struct{ gen.DO }

func (a ai_knowledge_baseDo) Debug() *ai_knowledge_baseDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_knowledge_baseDo) WithContext(ctx context.Context) *ai_knowledge_baseDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_knowledge_baseDo) ReadDB() *ai_knowledge_baseDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_knowledge_baseDo) WriteDB() *ai_knowledge_baseDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_knowledge_baseDo) Session(config *gorm.Session) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_knowledge_baseDo) Clauses(conds ...clause.Expression) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_knowledge_baseDo) Returning(value interface{}, columns ...string) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_knowledge_baseDo) Not(conds ...gen.Condition) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_knowledge_baseDo) Or(conds ...gen.Condition) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_knowledge_baseDo) Select(conds ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_knowledge_baseDo) Where(conds ...gen.Condition) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_knowledge_baseDo) Order(conds ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_knowledge_baseDo) Distinct(cols ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_knowledge_baseDo) Omit(cols ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_knowledge_baseDo) Join(table schema.Tabler, on ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_knowledge_baseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_knowledge_baseDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_knowledge_baseDo) Group(cols ...field.Expr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_knowledge_baseDo) Having(conds ...gen.Condition) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_knowledge_baseDo) Limit(limit int) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_knowledge_baseDo) Offset(offset int) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_knowledge_baseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_knowledge_baseDo) Unscoped() *ai_knowledge_baseDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_knowledge_baseDo) Create(values ...*model.Ai_knowledge_base) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_knowledge_baseDo) CreateInBatches(values []*model.Ai_knowledge_base, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_knowledge_baseDo) Save(values ...*model.Ai_knowledge_base) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_knowledge_baseDo) First() (*model.Ai_knowledge_base, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_base), nil
	}
}

func (a ai_knowledge_baseDo) Take() (*model.Ai_knowledge_base, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_base), nil
	}
}

func (a ai_knowledge_baseDo) Last() (*model.Ai_knowledge_base, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_base), nil
	}
}

func (a ai_knowledge_baseDo) Find() ([]*model.Ai_knowledge_base, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_knowledge_base), err
}

func (a ai_knowledge_baseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_knowledge_base, err error) {
	buf := make([]*model.Ai_knowledge_base, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_knowledge_baseDo) FindInBatches(result *[]*model.Ai_knowledge_base, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_knowledge_baseDo) Attrs(attrs ...field.AssignExpr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_knowledge_baseDo) Assign(attrs ...field.AssignExpr) *ai_knowledge_baseDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_knowledge_baseDo) Joins(fields ...field.RelationField) *ai_knowledge_baseDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_knowledge_baseDo) Preload(fields ...field.RelationField) *ai_knowledge_baseDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_knowledge_baseDo) FirstOrInit() (*model.Ai_knowledge_base, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_base), nil
	}
}

func (a ai_knowledge_baseDo) FirstOrCreate() (*model.Ai_knowledge_base, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_base), nil
	}
}

func (a ai_knowledge_baseDo) FindByPage(offset int, limit int) (result []*model.Ai_knowledge_base, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_knowledge_baseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_knowledge_baseDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_knowledge_baseDo) Delete(models ...*model.Ai_knowledge_base) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_knowledge_baseDo) withDO(do gen.Dao) *ai_knowledge_baseDo {
	a.DO = *do.(*gen.DO)
	return a
}
