// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_knowledge_documents(db *gorm.DB, opts ...gen.DOOption) ai_knowledge_documents {
	_ai_knowledge_documents := ai_knowledge_documents{}

	_ai_knowledge_documents.ai_knowledge_documentsDo.UseDB(db, opts...)
	_ai_knowledge_documents.ai_knowledge_documentsDo.UseModel(&model.Ai_knowledge_documents{})

	tableName := _ai_knowledge_documents.ai_knowledge_documentsDo.TableName()
	_ai_knowledge_documents.ALL = field.NewAsterisk(tableName)
	_ai_knowledge_documents.ID = field.NewInt64(tableName, "id")
	_ai_knowledge_documents.KnowledgeBaseName = field.NewString(tableName, "knowledge_base_name")
	_ai_knowledge_documents.FileName = field.NewString(tableName, "file_name")
	_ai_knowledge_documents.Status = field.NewInt32(tableName, "status")
	_ai_knowledge_documents.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_knowledge_documents.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_knowledge_documents.fillFieldMap()

	return _ai_knowledge_documents
}

// ai_knowledge_documents 知识库文档表
type ai_knowledge_documents struct {
	ai_knowledge_documentsDo ai_knowledge_documentsDo

	ALL               field.Asterisk
	ID                field.Int64
	KnowledgeBaseName field.String
	FileName          field.String
	Status            field.Int32
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (a ai_knowledge_documents) Table(newTableName string) *ai_knowledge_documents {
	a.ai_knowledge_documentsDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_knowledge_documents) As(alias string) *ai_knowledge_documents {
	a.ai_knowledge_documentsDo.DO = *(a.ai_knowledge_documentsDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_knowledge_documents) updateTableName(table string) *ai_knowledge_documents {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.KnowledgeBaseName = field.NewString(table, "knowledge_base_name")
	a.FileName = field.NewString(table, "file_name")
	a.Status = field.NewInt32(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_knowledge_documents) WithContext(ctx context.Context) *ai_knowledge_documentsDo {
	return a.ai_knowledge_documentsDo.WithContext(ctx)
}

func (a ai_knowledge_documents) TableName() string { return a.ai_knowledge_documentsDo.TableName() }

func (a ai_knowledge_documents) Alias() string { return a.ai_knowledge_documentsDo.Alias() }

func (a ai_knowledge_documents) Columns(cols ...field.Expr) gen.Columns {
	return a.ai_knowledge_documentsDo.Columns(cols...)
}

func (a *ai_knowledge_documents) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_knowledge_documents) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["knowledge_base_name"] = a.KnowledgeBaseName
	a.fieldMap["file_name"] = a.FileName
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_knowledge_documents) clone(db *gorm.DB) ai_knowledge_documents {
	a.ai_knowledge_documentsDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_knowledge_documents) replaceDB(db *gorm.DB) ai_knowledge_documents {
	a.ai_knowledge_documentsDo.ReplaceDB(db)
	return a
}

type ai_knowledge_documentsDo struct{ gen.DO }

func (a ai_knowledge_documentsDo) Debug() *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_knowledge_documentsDo) WithContext(ctx context.Context) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_knowledge_documentsDo) ReadDB() *ai_knowledge_documentsDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_knowledge_documentsDo) WriteDB() *ai_knowledge_documentsDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_knowledge_documentsDo) Session(config *gorm.Session) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_knowledge_documentsDo) Clauses(conds ...clause.Expression) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_knowledge_documentsDo) Returning(value interface{}, columns ...string) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_knowledge_documentsDo) Not(conds ...gen.Condition) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_knowledge_documentsDo) Or(conds ...gen.Condition) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_knowledge_documentsDo) Select(conds ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_knowledge_documentsDo) Where(conds ...gen.Condition) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_knowledge_documentsDo) Order(conds ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_knowledge_documentsDo) Distinct(cols ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_knowledge_documentsDo) Omit(cols ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_knowledge_documentsDo) Join(table schema.Tabler, on ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_knowledge_documentsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_knowledge_documentsDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_knowledge_documentsDo) Group(cols ...field.Expr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_knowledge_documentsDo) Having(conds ...gen.Condition) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_knowledge_documentsDo) Limit(limit int) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_knowledge_documentsDo) Offset(offset int) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_knowledge_documentsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_knowledge_documentsDo) Unscoped() *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_knowledge_documentsDo) Create(values ...*model.Ai_knowledge_documents) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_knowledge_documentsDo) CreateInBatches(values []*model.Ai_knowledge_documents, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_knowledge_documentsDo) Save(values ...*model.Ai_knowledge_documents) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_knowledge_documentsDo) First() (*model.Ai_knowledge_documents, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_documents), nil
	}
}

func (a ai_knowledge_documentsDo) Take() (*model.Ai_knowledge_documents, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_documents), nil
	}
}

func (a ai_knowledge_documentsDo) Last() (*model.Ai_knowledge_documents, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_documents), nil
	}
}

func (a ai_knowledge_documentsDo) Find() ([]*model.Ai_knowledge_documents, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_knowledge_documents), err
}

func (a ai_knowledge_documentsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_knowledge_documents, err error) {
	buf := make([]*model.Ai_knowledge_documents, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_knowledge_documentsDo) FindInBatches(result *[]*model.Ai_knowledge_documents, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_knowledge_documentsDo) Attrs(attrs ...field.AssignExpr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_knowledge_documentsDo) Assign(attrs ...field.AssignExpr) *ai_knowledge_documentsDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_knowledge_documentsDo) Joins(fields ...field.RelationField) *ai_knowledge_documentsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_knowledge_documentsDo) Preload(fields ...field.RelationField) *ai_knowledge_documentsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_knowledge_documentsDo) FirstOrInit() (*model.Ai_knowledge_documents, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_documents), nil
	}
}

func (a ai_knowledge_documentsDo) FirstOrCreate() (*model.Ai_knowledge_documents, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_knowledge_documents), nil
	}
}

func (a ai_knowledge_documentsDo) FindByPage(offset int, limit int) (result []*model.Ai_knowledge_documents, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_knowledge_documentsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_knowledge_documentsDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_knowledge_documentsDo) Delete(models ...*model.Ai_knowledge_documents) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_knowledge_documentsDo) withDO(do gen.Dao) *ai_knowledge_documentsDo {
	a.DO = *do.(*gen.DO)
	return a
}
