// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_mcp(db *gorm.DB, opts ...gen.DOOption) ai_mcp {
	_ai_mcp := ai_mcp{}

	_ai_mcp.ai_mcpDo.UseDB(db, opts...)
	_ai_mcp.ai_mcpDo.UseModel(&model.Ai_mcp{})

	tableName := _ai_mcp.ai_mcpDo.TableName()
	_ai_mcp.ALL = field.NewAsterisk(tableName)
	_ai_mcp.ID = field.NewString(tableName, "id")
	_ai_mcp.Type = field.NewInt32(tableName, "type")
	_ai_mcp.Enable = field.NewInt32(tableName, "enable")
	_ai_mcp.Name = field.NewString(tableName, "name")
	_ai_mcp.Des = field.NewString(tableName, "des")
	_ai_mcp.Version = field.NewString(tableName, "version")
	_ai_mcp.Option = field.NewString(tableName, "option")
	_ai_mcp.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_mcp.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_mcp.fillFieldMap()

	return _ai_mcp
}

// ai_mcp MCP服务表
type ai_mcp struct {
	ai_mcpDo ai_mcpDo

	ALL       field.Asterisk
	ID        field.String // id
	Type      field.Int32  // 类型：0:未知;1:内部;2:外部;3:第3方
	Enable    field.Int32  // 是否使用
	Name      field.String // mcp服务器名称
	Des       field.String // 描述
	Version   field.String // 版本
	Option    field.String // 配置项
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a ai_mcp) Table(newTableName string) *ai_mcp {
	a.ai_mcpDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_mcp) As(alias string) *ai_mcp {
	a.ai_mcpDo.DO = *(a.ai_mcpDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_mcp) updateTableName(table string) *ai_mcp {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.Type = field.NewInt32(table, "type")
	a.Enable = field.NewInt32(table, "enable")
	a.Name = field.NewString(table, "name")
	a.Des = field.NewString(table, "des")
	a.Version = field.NewString(table, "version")
	a.Option = field.NewString(table, "option")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_mcp) WithContext(ctx context.Context) *ai_mcpDo { return a.ai_mcpDo.WithContext(ctx) }

func (a ai_mcp) TableName() string { return a.ai_mcpDo.TableName() }

func (a ai_mcp) Alias() string { return a.ai_mcpDo.Alias() }

func (a ai_mcp) Columns(cols ...field.Expr) gen.Columns { return a.ai_mcpDo.Columns(cols...) }

func (a *ai_mcp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_mcp) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["type"] = a.Type
	a.fieldMap["enable"] = a.Enable
	a.fieldMap["name"] = a.Name
	a.fieldMap["des"] = a.Des
	a.fieldMap["version"] = a.Version
	a.fieldMap["option"] = a.Option
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_mcp) clone(db *gorm.DB) ai_mcp {
	a.ai_mcpDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_mcp) replaceDB(db *gorm.DB) ai_mcp {
	a.ai_mcpDo.ReplaceDB(db)
	return a
}

type ai_mcpDo struct{ gen.DO }

func (a ai_mcpDo) Debug() *ai_mcpDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_mcpDo) WithContext(ctx context.Context) *ai_mcpDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_mcpDo) ReadDB() *ai_mcpDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_mcpDo) WriteDB() *ai_mcpDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_mcpDo) Session(config *gorm.Session) *ai_mcpDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_mcpDo) Clauses(conds ...clause.Expression) *ai_mcpDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_mcpDo) Returning(value interface{}, columns ...string) *ai_mcpDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_mcpDo) Not(conds ...gen.Condition) *ai_mcpDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_mcpDo) Or(conds ...gen.Condition) *ai_mcpDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_mcpDo) Select(conds ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_mcpDo) Where(conds ...gen.Condition) *ai_mcpDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_mcpDo) Order(conds ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_mcpDo) Distinct(cols ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_mcpDo) Omit(cols ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_mcpDo) Join(table schema.Tabler, on ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_mcpDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_mcpDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_mcpDo) Group(cols ...field.Expr) *ai_mcpDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_mcpDo) Having(conds ...gen.Condition) *ai_mcpDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_mcpDo) Limit(limit int) *ai_mcpDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_mcpDo) Offset(offset int) *ai_mcpDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_mcpDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_mcpDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_mcpDo) Unscoped() *ai_mcpDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_mcpDo) Create(values ...*model.Ai_mcp) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_mcpDo) CreateInBatches(values []*model.Ai_mcp, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_mcpDo) Save(values ...*model.Ai_mcp) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_mcpDo) First() (*model.Ai_mcp, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_mcp), nil
	}
}

func (a ai_mcpDo) Take() (*model.Ai_mcp, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_mcp), nil
	}
}

func (a ai_mcpDo) Last() (*model.Ai_mcp, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_mcp), nil
	}
}

func (a ai_mcpDo) Find() ([]*model.Ai_mcp, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_mcp), err
}

func (a ai_mcpDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_mcp, err error) {
	buf := make([]*model.Ai_mcp, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_mcpDo) FindInBatches(result *[]*model.Ai_mcp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_mcpDo) Attrs(attrs ...field.AssignExpr) *ai_mcpDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_mcpDo) Assign(attrs ...field.AssignExpr) *ai_mcpDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_mcpDo) Joins(fields ...field.RelationField) *ai_mcpDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_mcpDo) Preload(fields ...field.RelationField) *ai_mcpDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_mcpDo) FirstOrInit() (*model.Ai_mcp, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_mcp), nil
	}
}

func (a ai_mcpDo) FirstOrCreate() (*model.Ai_mcp, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_mcp), nil
	}
}

func (a ai_mcpDo) FindByPage(offset int, limit int) (result []*model.Ai_mcp, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_mcpDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_mcpDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_mcpDo) Delete(models ...*model.Ai_mcp) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_mcpDo) withDO(do gen.Dao) *ai_mcpDo {
	a.DO = *do.(*gen.DO)
	return a
}
