// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_session_logs(db *gorm.DB, opts ...gen.DOOption) ai_session_logs {
	_ai_session_logs := ai_session_logs{}

	_ai_session_logs.ai_session_logsDo.UseDB(db, opts...)
	_ai_session_logs.ai_session_logsDo.UseModel(&model.Ai_session_logs{})

	tableName := _ai_session_logs.ai_session_logsDo.TableName()
	_ai_session_logs.ALL = field.NewAsterisk(tableName)
	_ai_session_logs.ID = field.NewString(tableName, "id")
	_ai_session_logs.UserID = field.NewString(tableName, "user_id")
	_ai_session_logs.PromptID = field.NewString(tableName, "prompt_id")
	_ai_session_logs.LastAt = field.NewTime(tableName, "last_at")

	_ai_session_logs.fillFieldMap()

	return _ai_session_logs
}

// ai_session_logs 会话记录表
type ai_session_logs struct {
	ai_session_logsDo ai_session_logsDo

	ALL      field.Asterisk
	ID       field.String // 会话记录id
	UserID   field.String // 用户id
	PromptID field.String // 提示词模板id
	LastAt   field.Time   // 最后时间

	fieldMap map[string]field.Expr
}

func (a ai_session_logs) Table(newTableName string) *ai_session_logs {
	a.ai_session_logsDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_session_logs) As(alias string) *ai_session_logs {
	a.ai_session_logsDo.DO = *(a.ai_session_logsDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_session_logs) updateTableName(table string) *ai_session_logs {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewString(table, "user_id")
	a.PromptID = field.NewString(table, "prompt_id")
	a.LastAt = field.NewTime(table, "last_at")

	a.fillFieldMap()

	return a
}

func (a *ai_session_logs) WithContext(ctx context.Context) *ai_session_logsDo {
	return a.ai_session_logsDo.WithContext(ctx)
}

func (a ai_session_logs) TableName() string { return a.ai_session_logsDo.TableName() }

func (a ai_session_logs) Alias() string { return a.ai_session_logsDo.Alias() }

func (a ai_session_logs) Columns(cols ...field.Expr) gen.Columns {
	return a.ai_session_logsDo.Columns(cols...)
}

func (a *ai_session_logs) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_session_logs) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["prompt_id"] = a.PromptID
	a.fieldMap["last_at"] = a.LastAt
}

func (a ai_session_logs) clone(db *gorm.DB) ai_session_logs {
	a.ai_session_logsDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_session_logs) replaceDB(db *gorm.DB) ai_session_logs {
	a.ai_session_logsDo.ReplaceDB(db)
	return a
}

type ai_session_logsDo struct{ gen.DO }

func (a ai_session_logsDo) Debug() *ai_session_logsDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_session_logsDo) WithContext(ctx context.Context) *ai_session_logsDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_session_logsDo) ReadDB() *ai_session_logsDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_session_logsDo) WriteDB() *ai_session_logsDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_session_logsDo) Session(config *gorm.Session) *ai_session_logsDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_session_logsDo) Clauses(conds ...clause.Expression) *ai_session_logsDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_session_logsDo) Returning(value interface{}, columns ...string) *ai_session_logsDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_session_logsDo) Not(conds ...gen.Condition) *ai_session_logsDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_session_logsDo) Or(conds ...gen.Condition) *ai_session_logsDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_session_logsDo) Select(conds ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_session_logsDo) Where(conds ...gen.Condition) *ai_session_logsDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_session_logsDo) Order(conds ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_session_logsDo) Distinct(cols ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_session_logsDo) Omit(cols ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_session_logsDo) Join(table schema.Tabler, on ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_session_logsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_session_logsDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_session_logsDo) Group(cols ...field.Expr) *ai_session_logsDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_session_logsDo) Having(conds ...gen.Condition) *ai_session_logsDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_session_logsDo) Limit(limit int) *ai_session_logsDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_session_logsDo) Offset(offset int) *ai_session_logsDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_session_logsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_session_logsDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_session_logsDo) Unscoped() *ai_session_logsDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_session_logsDo) Create(values ...*model.Ai_session_logs) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_session_logsDo) CreateInBatches(values []*model.Ai_session_logs, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_session_logsDo) Save(values ...*model.Ai_session_logs) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_session_logsDo) First() (*model.Ai_session_logs, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_session_logs), nil
	}
}

func (a ai_session_logsDo) Take() (*model.Ai_session_logs, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_session_logs), nil
	}
}

func (a ai_session_logsDo) Last() (*model.Ai_session_logs, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_session_logs), nil
	}
}

func (a ai_session_logsDo) Find() ([]*model.Ai_session_logs, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_session_logs), err
}

func (a ai_session_logsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_session_logs, err error) {
	buf := make([]*model.Ai_session_logs, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_session_logsDo) FindInBatches(result *[]*model.Ai_session_logs, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_session_logsDo) Attrs(attrs ...field.AssignExpr) *ai_session_logsDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_session_logsDo) Assign(attrs ...field.AssignExpr) *ai_session_logsDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_session_logsDo) Joins(fields ...field.RelationField) *ai_session_logsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_session_logsDo) Preload(fields ...field.RelationField) *ai_session_logsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_session_logsDo) FirstOrInit() (*model.Ai_session_logs, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_session_logs), nil
	}
}

func (a ai_session_logsDo) FirstOrCreate() (*model.Ai_session_logs, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_session_logs), nil
	}
}

func (a ai_session_logsDo) FindByPage(offset int, limit int) (result []*model.Ai_session_logs, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_session_logsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_session_logsDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_session_logsDo) Delete(models ...*model.Ai_session_logs) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_session_logsDo) withDO(do gen.Dao) *ai_session_logsDo {
	a.DO = *do.(*gen.DO)
	return a
}
