// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_tool(db *gorm.DB, opts ...gen.DOOption) ai_tool {
	_ai_tool := ai_tool{}

	_ai_tool.ai_toolDo.UseDB(db, opts...)
	_ai_tool.ai_toolDo.UseModel(&model.Ai_tool{})

	tableName := _ai_tool.ai_toolDo.TableName()
	_ai_tool.ALL = field.NewAsterisk(tableName)
	_ai_tool.ID = field.NewString(tableName, "id")
	_ai_tool.Enable = field.NewBool(tableName, "enable")
	_ai_tool.Name = field.NewString(tableName, "name")
	_ai_tool.Des = field.NewString(tableName, "des")
	_ai_tool.McpID = field.NewString(tableName, "mcp_id")
	_ai_tool.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_tool.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_tool.fillFieldMap()

	return _ai_tool
}

// ai_tool 工具信息表
type ai_tool struct {
	ai_toolDo ai_toolDo

	ALL       field.Asterisk
	ID        field.String // 雪花ID（字符串类型），唯一标识记录
	Enable    field.Bool   // 是否启用（1=是，0=否）
	Name      field.String // 工具名称
	Des       field.String // 工具描述
	McpID     field.String // 所属MCP服务器id
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a ai_tool) Table(newTableName string) *ai_tool {
	a.ai_toolDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_tool) As(alias string) *ai_tool {
	a.ai_toolDo.DO = *(a.ai_toolDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_tool) updateTableName(table string) *ai_tool {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.Enable = field.NewBool(table, "enable")
	a.Name = field.NewString(table, "name")
	a.Des = field.NewString(table, "des")
	a.McpID = field.NewString(table, "mcp_id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_tool) WithContext(ctx context.Context) *ai_toolDo { return a.ai_toolDo.WithContext(ctx) }

func (a ai_tool) TableName() string { return a.ai_toolDo.TableName() }

func (a ai_tool) Alias() string { return a.ai_toolDo.Alias() }

func (a ai_tool) Columns(cols ...field.Expr) gen.Columns { return a.ai_toolDo.Columns(cols...) }

func (a *ai_tool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_tool) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["enable"] = a.Enable
	a.fieldMap["name"] = a.Name
	a.fieldMap["des"] = a.Des
	a.fieldMap["mcp_id"] = a.McpID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_tool) clone(db *gorm.DB) ai_tool {
	a.ai_toolDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_tool) replaceDB(db *gorm.DB) ai_tool {
	a.ai_toolDo.ReplaceDB(db)
	return a
}

type ai_toolDo struct{ gen.DO }

func (a ai_toolDo) Debug() *ai_toolDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_toolDo) WithContext(ctx context.Context) *ai_toolDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_toolDo) ReadDB() *ai_toolDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_toolDo) WriteDB() *ai_toolDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_toolDo) Session(config *gorm.Session) *ai_toolDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_toolDo) Clauses(conds ...clause.Expression) *ai_toolDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_toolDo) Returning(value interface{}, columns ...string) *ai_toolDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_toolDo) Not(conds ...gen.Condition) *ai_toolDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_toolDo) Or(conds ...gen.Condition) *ai_toolDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_toolDo) Select(conds ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_toolDo) Where(conds ...gen.Condition) *ai_toolDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_toolDo) Order(conds ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_toolDo) Distinct(cols ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_toolDo) Omit(cols ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_toolDo) Join(table schema.Tabler, on ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_toolDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_toolDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_toolDo) Group(cols ...field.Expr) *ai_toolDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_toolDo) Having(conds ...gen.Condition) *ai_toolDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_toolDo) Limit(limit int) *ai_toolDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_toolDo) Offset(offset int) *ai_toolDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_toolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_toolDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_toolDo) Unscoped() *ai_toolDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_toolDo) Create(values ...*model.Ai_tool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_toolDo) CreateInBatches(values []*model.Ai_tool, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_toolDo) Save(values ...*model.Ai_tool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_toolDo) First() (*model.Ai_tool, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_tool), nil
	}
}

func (a ai_toolDo) Take() (*model.Ai_tool, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_tool), nil
	}
}

func (a ai_toolDo) Last() (*model.Ai_tool, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_tool), nil
	}
}

func (a ai_toolDo) Find() ([]*model.Ai_tool, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_tool), err
}

func (a ai_toolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_tool, err error) {
	buf := make([]*model.Ai_tool, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_toolDo) FindInBatches(result *[]*model.Ai_tool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_toolDo) Attrs(attrs ...field.AssignExpr) *ai_toolDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_toolDo) Assign(attrs ...field.AssignExpr) *ai_toolDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_toolDo) Joins(fields ...field.RelationField) *ai_toolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_toolDo) Preload(fields ...field.RelationField) *ai_toolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_toolDo) FirstOrInit() (*model.Ai_tool, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_tool), nil
	}
}

func (a ai_toolDo) FirstOrCreate() (*model.Ai_tool, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_tool), nil
	}
}

func (a ai_toolDo) FindByPage(offset int, limit int) (result []*model.Ai_tool, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_toolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_toolDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_toolDo) Delete(models ...*model.Ai_tool) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_toolDo) withDO(do gen.Dao) *ai_toolDo {
	a.DO = *do.(*gen.DO)
	return a
}
