// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_knowledge_chunks = "ai_knowledge_chunks"

// Ai_knowledge_chunks 知识库文档切片表
type Ai_knowledge_chunks struct {
	ID             int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	KnowledgeDocID int64      `gorm:"column:knowledge_doc_id;type:bigint;primaryKey;index:idx_knowledge_chunks_knowledge_doc_id,priority:1" json:"knowledge_doc_id"`
	ChunkID        string     `gorm:"column:chunk_id;type:varchar(36);not null;uniqueIndex:uk_chunk_id,priority:1" json:"chunk_id"`
	Content        string     `gorm:"column:content;type:text" json:"content"`
	Ext            string     `gorm:"column:ext;type:varchar(1024)" json:"ext"`
	Status         *bool      `gorm:"column:status;type:tinyint(1);not null;default:1" json:"status"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName Ai_knowledge_chunks's table name
func (*Ai_knowledge_chunks) TableName() string {
	return TableNameAi_knowledge_chunks
}
