// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm"
)

// Ai_knowledge_base_QueryReq 是用于查询 Ai_knowledge_base 表的请求结构体
type Ai_knowledge_base_QueryReq struct {
	//
	Category *string `json:"Category" column:"category" form:"Category"`
	//
	CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
	//
	Description *string `json:"Description" column:"description" form:"Description"`
	//
	ID *string `json:"ID" column:"id" form:"ID"`
	//
	Name *string `json:"Name" column:"name" form:"Name"`
	//
	Status *string `json:"Status" column:"status" form:"Status"`
	//
	UpdatedAt *string `json:"UpdatedAt" column:"updated_at" form:"UpdatedAt"`
	// 排序字段，例如 "字段名 asc" 或 "字段名 desc"
	OrderBy *string `json:"OrderBy" form:"OrderBy"`
	// 是否模糊查询
	IsLike bool `json:"IsLike" form:"IsLike"`
	// 分页信息
	Page *dbm.Page `json:"Page" form:"Page"`
}
