// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_knowledge_base = "ai_knowledge_base"

// Ai_knowledge_base 知识库基础表
type Ai_knowledge_base struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(255)" json:"name"`
	Description string    `gorm:"column:description;type:varchar(255)" json:"description"`
	Category    string    `gorm:"column:category;type:varchar(255)" json:"category"`
	Status      *int64    `gorm:"column:status;type:bigint;default:1" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Ai_knowledge_base's table name
func (*Ai_knowledge_base) TableName() string {
	return TableNameAi_knowledge_base
}
