// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm"
)

// Ai_knowledge_documents_QueryReq 是用于查询 Ai_knowledge_documents 表的请求结构体
type Ai_knowledge_documents_QueryReq struct {
	//
	CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
	//
	FileName *string `json:"FileName" column:"file_name" form:"FileName"`
	//
	ID *string `json:"ID" column:"id" form:"ID"`
	//
	KnowledgeBaseName *string `json:"KnowledgeBaseName" column:"knowledge_base_name" form:"KnowledgeBaseName"`
	//
	Status *string `json:"Status" column:"status" form:"Status"`
	//
	UpdatedAt *string `json:"UpdatedAt" column:"updated_at" form:"UpdatedAt"`
	// 排序字段，例如 "字段名 asc" 或 "字段名 desc"
	OrderBy *string `json:"OrderBy" form:"OrderBy"`
	// 是否模糊查询
	IsLike bool `json:"IsLike" form:"IsLike"`
	// 分页信息
	Page *dbm.Page `json:"Page" form:"Page"`
}
