// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_knowledge_documents = "ai_knowledge_documents"

// Ai_knowledge_documents 知识库文档表
type Ai_knowledge_documents struct {
	ID                int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	KnowledgeBaseName string     `gorm:"column:knowledge_base_name;type:varchar(255);not null" json:"knowledge_base_name"`
	FileName          string     `gorm:"column:file_name;type:varchar(255)" json:"file_name"`
	Status            int32      `gorm:"column:status;type:tinyint;not null" json:"status"`
	CreatedAt         *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Ai_knowledge_documents's table name
func (*Ai_knowledge_documents) TableName() string {
	return TableNameAi_knowledge_documents
}
