// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm"
)

// Ai_mcp_QueryReq 是用于查询 Ai_mcp 表的请求结构体
type Ai_mcp_QueryReq struct {
	// 创建时间
	CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
	// 描述
	Des *string `json:"Des" column:"des" form:"Des"`
	// 是否使用
	Enable *string `json:"Enable" column:"enable" form:"Enable"`
	// id
	ID *string `json:"ID" column:"id" form:"ID"`
	// mcp服务器名称
	Name *string `json:"Name" column:"name" form:"Name"`
	// 配置项
	Option *string `json:"Option" column:"option" form:"Option"`
	// 类型：0:未知;1:内部;2:外部;3:第3方
	Type *string `json:"Type" column:"type" form:"Type"`
	// 更新时间
	UpdatedAt *string `json:"UpdatedAt" column:"updated_at" form:"UpdatedAt"`
	// 版本
	Version *string `json:"Version" column:"version" form:"Version"`
	// 排序字段，例如 "字段名 asc" 或 "字段名 desc"
	OrderBy *string `json:"OrderBy" form:"OrderBy"`
	// 是否模糊查询
	IsLike bool `json:"IsLike" form:"IsLike"`
	// 分页信息
	Page *dbm.Page `json:"Page" form:"Page"`
}
