// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_mcp = "ai_mcp"

// Ai_mcp MCP服务表
type Ai_mcp struct {
	ID        string    `gorm:"column:id;type:varchar(64);primaryKey;comment:id" json:"id"`                // id
	Type      int32     `gorm:"column:type;type:int;not null;comment:类型：0:未知;1:内部;2:外部;3:第3方" json:"type"` // 类型：0:未知;1:内部;2:外部;3:第3方
	Enable    bool      `gorm:"column:enable;type:tinyint(1);not null;default:1" json:"enable"`            // 是否使用
	Name      string    `gorm:"column:name;type:varchar(100);not null;comment:mcp服务器名称" json:"name"`       // mcp服务器名称
	Des       string    `gorm:"column:des;type:varchar(250);not null;comment:描述" json:"des"`               // 描述
	Version   string    `gorm:"column:version;type:varchar(100);comment:版本" json:"version"`                // 版本
	Option    string    `gorm:"column:option;type:varchar(250);not null;comment:配置项" json:"option"`        // 配置项
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`            // 更新时间
}

// TableName Ai_mcp's table name
func (*Ai_mcp) TableName() string {
	return TableNameAi_mcp
}
