// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm"
)

// Ai_tool_QueryReq 是用于查询 Ai_tool 表的请求结构体
type Ai_tool_QueryReq struct {
	// 创建时间
	CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
	// 工具描述
	Des *string `json:"Des" column:"des" form:"Des"`
	// 是否启用（1=是，0=否）
	Enable *string `json:"Enable" column:"enable" form:"Enable"`
	// 雪花ID（字符串类型），唯一标识记录
	ID *string `json:"ID" column:"id" form:"ID"`
	// 所属MCP服务器id
	McpID *string `json:"McpID" column:"mcp_id" form:"McpID"`
	// 工具名称
	Name *string `json:"Name" column:"name" form:"Name"`
	// 更新时间
	UpdatedAt *string `json:"UpdatedAt" column:"updated_at" form:"UpdatedAt"`
	// 排序字段，例如 "字段名 asc" 或 "字段名 desc"
	OrderBy *string `json:"OrderBy" form:"OrderBy"`
	// 是否模糊查询
	IsLike bool `json:"IsLike" form:"IsLike"`
	// 分页信息
	Page *dbm.Page `json:"Page" form:"Page"`
}
