// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_tool = "ai_tool"

// Ai_tool 工具信息表
type Ai_tool struct {
	ID        string     `gorm:"column:id;type:varchar(64);primaryKey;comment:雪花ID（字符串类型），唯一标识记录" json:"id"`                                                        // 雪花ID（字符串类型），唯一标识记录
	Enable    bool       `gorm:"column:enable;type:tinyint(1);not null;default:1" json:"enable"`                                                                    // 是否启用（1=是，0=否）
	Name      string     `gorm:"column:name;type:varchar(255);not null;uniqueIndex:uk_tool_name,priority:1;comment:工具名称" json:"name"`                               // 工具名称
	Des       string     `gorm:"column:des;type:text;comment:工具描述" json:"des"`                                                                                      // 工具描述
	McpID     string     `gorm:"column:mcp_id;type:varchar(255);not null;index:fk_ai_tool_ai_mcp,priority:1;comment:所属MCP服务器id" json:"mcp_id"`                      // 所属MCP服务器id
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;not null;index:idx_updated_at,priority:1;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Ai_tool's table name
func (*Ai_tool) TableName() string {
	return TableNameAi_tool
}
