// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

func GetModels() []interface{} {
	m := make([]interface{}, 0)
	v0 := Ai_chat_logs{}
	m = append(m, v0)
	v1 := Ai_knowledge_base{}
	m = append(m, v1)
	v2 := Ai_knowledge_chunks{}
	m = append(m, v2)
	v3 := Ai_knowledge_documents{}
	m = append(m, v3)
	v4 := Ai_mcp{}
	m = append(m, v4)
	v5 := Ai_prompt{}
	m = append(m, v5)
	v6 := Ai_session_logs{}
	m = append(m, v6)
	v7 := Ai_tool{}
	m = append(m, v7)
	return m
}

func AutoMigrate(db *gorm.DB) error {
	if err := db.AutoMigrate(GetModels()...); err != nil {
		return err
	}
	return nil
}
