// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_knowledge_base_if

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/model"
)

type GenIf interface {
	// Add 新增
	Add(data ...*model.Ai_knowledge_base) error
	// Upt 更新
	Upt(data ...*model.Ai_knowledge_base) error
	// Save 保存
	Save(data ...*model.Ai_knowledge_base) error
	// Del 删除
	Del(data ...*model.Ai_knowledge_base) error
	// First 查询第一条
	First(query *model.Ai_knowledge_base) (data *model.Ai_knowledge_base, err error)
	// Find 通用查询
	Find(query *model.Ai_knowledge_base_QueryReq) (data []*model.Ai_knowledge_base, total int64, err error)
}
