base: # 基础配置
    node: 1 # 节点编号
    httpport: 7589 # Http服务端口
    tcpport: 7588 # Tcp服务端口
    lastexittime: 2025-07-16 23:06:19.7092855 +0800 CST m=+64.577032601 # 上次退出时间
log: # 日志配置
    name: sysLog # 日志器名称,系统覆盖,修改无效
    level: 0 # 日志记录级别：-1->Debug及以上;0->Info及以上;1->Warn及以上;2->Error及以上;3->DPanic及以上;4->Panic及以上;5->Fatal及以上;
    maxsize: 5 # 单个日志文件最大容量，单位:M,最小值1,最大值20
    maxage: 30 # 最大备份天数,最小值1,最大值1000
    maxbackups: 1000 # 日志备份最大数量,最小值1,最大值1024
    localtime: true # 是否使用本地时间
    compress: true # 是否压缩
    path: F:\03_Project\GoWorks\src\fmc-go-agent\bin/log # 日志文件存储路径(绝对路径)
db: # 数据库配置
    dbtype: mysql # 数据库类型,目前支持:mysql、mssql、dm
    host: localhost # 数据库服务的主机或IP
    port: 3306 # 数据库服务侦听的端口号
    account: root # 登录用户的帐号
    password: "123456" # 登录用户的密码
    isautomigrate: false # 是否自动迁移表结构
ext: # 外部服务配置
    usercenter: # 用户中心配置
        enable: false # 是否启用
        baseurl: # 基础URL
            - http://localhost:80
        timeout: 60 # 请求超时时间,单位s
        retrycount: 3 # 重试次数
        retrydelay: 100 # 重试间隔时间,单位ms
    mcpserver: null # MCP客户配置(MCP客户)
    usercenterroot: # 用户中心管理员配置
        username: admin # 用户中心管理员用户名
        password: sm3加密后字符串 # 用户中心管理员密码,sm3加密后密码字符串
ucm: # UChatModel配置,用于连接大模型
    apikey: "" # API-秘钥
    baseurl: http://192.168.53.217:11434 # API-链接
    organization: ut-pc2-gd # API-使用组织
    provider: ollama # API-模型提供商:OpenAI、Ollama、DeepSeek等支持OpenAi Api的厂商
    model: deepseek-r1:7b # API-应用模型
    timeout: 120 # API-超时时间
uirv: # UAIIRVector配置,用于意图识别的向量检索
    irvmodel: # 向量数据库使用的大模型配置
        apikey: ollama key # API-秘钥
        baseurl: http://192.168.53.217:11434 # API-链接
        organization: ut-pc2-gd # API-使用组织
        provider: ollama # API-模型提供商
        model: bge-m3:latest # API-应用模型
        timeout: 120 # API-超时时间
    redisstack: # 向量数据库RedisStack配置
        addr: 192.168.53.217:16379 # RedisStack地址,192.168.53.217:16789
        protocol: 2 # 协议类型,2
        dimension: 4096 # 对齐格式,4096
        db: 0 # 数据库索引,0
    loadmdfileploy: # 本地知识文档（*.md）加载策略
        isloadmdfiles: false # 是否加载本地文件到向量数据库
        dir: ./knowdb/md # 本地md文件路径
mcpserver: # MCP服务配置(MCP服务)
    type: streamable # 传输协议类型,sse、streamable、stdio
    command: ls # stdio传输协议的命令
    env: # stdio传输协议的环境变量
        - test
    args: # stdio传输协议的命令参数
        - test
    baseurl: http://localhost:7856/mcp # sse、streamable传输协议的远程链接,客户端配置到具体端点:http://localhost:7856/mcp,服务端配置到暴露端口：0.0.0.0:7856
    header: # sse、streamable传输协议的请求头
        Authorization: Bearer your-auth-token
        Content-Type: application/json
        authorization: Bearer your-auth-token
        content-type: application/json
    oauthconfig: null # sse、streamable传输协议的OAuth配置
msg: # 消息配置
    mainwss: # 主消息服务配置
        option:
            enable: false # 是否启用
            writewaitsecond: 30 # 写数据超时[秒]
            pongwaitsecond: 120 # 读数据超时[秒]
            maxmessagesize: 0 # 读数据最大缓冲区;0-为没有限制
            serviceport: 7896 # 服务侦听端口
            servicepattern: /ws # 服务路由目录
            isping: true # 是否从本服务端给客户端定时发ping
    mqtt: # MQTT消息服务配置
        enable: false # 是否启用
        broker: # Broker 地址
            - tcp://localhost:1883
        user: admin # 用户名
        password: Unitech@1998 # 密码
        subtopic: # 订阅的主题
            - ""
