// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gdb

import (
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/dbif"
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/dbif/urtyg_ai_agent_if"
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/dal/db/gdb/urtyg_ai_agent_gdb"
    "github.com/freedqo/fmc-go-agent/pkg/ugrom"
)

func New(opt *ugrom.Option) dbif.If {
	return &db{
		urtyg_ai_agent_gdb: urtyg_ai_agent_gdb.New(opt),
	}
}

type db struct {
	urtyg_ai_agent_gdb urtyg_ai_agent_if.If
}
func (d *db) Urtyg_ai_agent() urtyg_ai_agent_if.If {
	return d.urtyg_ai_agent_gdb
}
