// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/model/dalm/dbm/urtyg_ai_agent/model"
)

func newAi_prompt(db *gorm.DB, opts ...gen.DOOption) ai_prompt {
	_ai_prompt := ai_prompt{}

	_ai_prompt.ai_promptDo.UseDB(db, opts...)
	_ai_prompt.ai_promptDo.UseModel(&model.Ai_prompt{})

	tableName := _ai_prompt.ai_promptDo.TableName()
	_ai_prompt.ALL = field.NewAsterisk(tableName)
	_ai_prompt.ID = field.NewString(tableName, "id")
	_ai_prompt.UserID = field.NewString(tableName, "user_id")
	_ai_prompt.Type = field.NewString(tableName, "type")
	_ai_prompt.Name = field.NewString(tableName, "name")
	_ai_prompt.Description = field.NewString(tableName, "description")
	_ai_prompt.Content = field.NewString(tableName, "content")
	_ai_prompt.IsShared = field.NewBool(tableName, "is_shared")
	_ai_prompt.SharedAt = field.NewTime(tableName, "shared_at")
	_ai_prompt.CreatedAt = field.NewTime(tableName, "created_at")
	_ai_prompt.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ai_prompt.fillFieldMap()

	return _ai_prompt
}

// ai_prompt 用户提示词模板表
type ai_prompt struct {
	ai_promptDo ai_promptDo

	ALL         field.Asterisk
	ID          field.String // 模板唯一ID
	UserID      field.String // 创建用户ID
	Type        field.String // 模板类型
	Name        field.String // 模板名称
	Description field.String // 模板描述
	Content     field.String // 模板内容(md格式)
	IsShared    field.Bool   // 是否分享(0-私有,1-公开)
	SharedAt    field.Time   // 分享时间
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a ai_prompt) Table(newTableName string) *ai_prompt {
	a.ai_promptDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a ai_prompt) As(alias string) *ai_prompt {
	a.ai_promptDo.DO = *(a.ai_promptDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *ai_prompt) updateTableName(table string) *ai_prompt {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewString(table, "user_id")
	a.Type = field.NewString(table, "type")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")
	a.Content = field.NewString(table, "content")
	a.IsShared = field.NewBool(table, "is_shared")
	a.SharedAt = field.NewTime(table, "shared_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *ai_prompt) WithContext(ctx context.Context) *ai_promptDo {
	return a.ai_promptDo.WithContext(ctx)
}

func (a ai_prompt) TableName() string { return a.ai_promptDo.TableName() }

func (a ai_prompt) Alias() string { return a.ai_promptDo.Alias() }

func (a ai_prompt) Columns(cols ...field.Expr) gen.Columns { return a.ai_promptDo.Columns(cols...) }

func (a *ai_prompt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *ai_prompt) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["type"] = a.Type
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description
	a.fieldMap["content"] = a.Content
	a.fieldMap["is_shared"] = a.IsShared
	a.fieldMap["shared_at"] = a.SharedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a ai_prompt) clone(db *gorm.DB) ai_prompt {
	a.ai_promptDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a ai_prompt) replaceDB(db *gorm.DB) ai_prompt {
	a.ai_promptDo.ReplaceDB(db)
	return a
}

type ai_promptDo struct{ gen.DO }

func (a ai_promptDo) Debug() *ai_promptDo {
	return a.withDO(a.DO.Debug())
}

func (a ai_promptDo) WithContext(ctx context.Context) *ai_promptDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a ai_promptDo) ReadDB() *ai_promptDo {
	return a.Clauses(dbresolver.Read)
}

func (a ai_promptDo) WriteDB() *ai_promptDo {
	return a.Clauses(dbresolver.Write)
}

func (a ai_promptDo) Session(config *gorm.Session) *ai_promptDo {
	return a.withDO(a.DO.Session(config))
}

func (a ai_promptDo) Clauses(conds ...clause.Expression) *ai_promptDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a ai_promptDo) Returning(value interface{}, columns ...string) *ai_promptDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a ai_promptDo) Not(conds ...gen.Condition) *ai_promptDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a ai_promptDo) Or(conds ...gen.Condition) *ai_promptDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a ai_promptDo) Select(conds ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a ai_promptDo) Where(conds ...gen.Condition) *ai_promptDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a ai_promptDo) Order(conds ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a ai_promptDo) Distinct(cols ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a ai_promptDo) Omit(cols ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a ai_promptDo) Join(table schema.Tabler, on ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a ai_promptDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a ai_promptDo) RightJoin(table schema.Tabler, on ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a ai_promptDo) Group(cols ...field.Expr) *ai_promptDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a ai_promptDo) Having(conds ...gen.Condition) *ai_promptDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a ai_promptDo) Limit(limit int) *ai_promptDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a ai_promptDo) Offset(offset int) *ai_promptDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a ai_promptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ai_promptDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a ai_promptDo) Unscoped() *ai_promptDo {
	return a.withDO(a.DO.Unscoped())
}

func (a ai_promptDo) Create(values ...*model.Ai_prompt) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a ai_promptDo) CreateInBatches(values []*model.Ai_prompt, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a ai_promptDo) Save(values ...*model.Ai_prompt) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a ai_promptDo) First() (*model.Ai_prompt, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_prompt), nil
	}
}

func (a ai_promptDo) Take() (*model.Ai_prompt, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_prompt), nil
	}
}

func (a ai_promptDo) Last() (*model.Ai_prompt, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_prompt), nil
	}
}

func (a ai_promptDo) Find() ([]*model.Ai_prompt, error) {
	result, err := a.DO.Find()
	return result.([]*model.Ai_prompt), err
}

func (a ai_promptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ai_prompt, err error) {
	buf := make([]*model.Ai_prompt, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a ai_promptDo) FindInBatches(result *[]*model.Ai_prompt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a ai_promptDo) Attrs(attrs ...field.AssignExpr) *ai_promptDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a ai_promptDo) Assign(attrs ...field.AssignExpr) *ai_promptDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a ai_promptDo) Joins(fields ...field.RelationField) *ai_promptDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a ai_promptDo) Preload(fields ...field.RelationField) *ai_promptDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a ai_promptDo) FirstOrInit() (*model.Ai_prompt, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_prompt), nil
	}
}

func (a ai_promptDo) FirstOrCreate() (*model.Ai_prompt, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ai_prompt), nil
	}
}

func (a ai_promptDo) FindByPage(offset int, limit int) (result []*model.Ai_prompt, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a ai_promptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a ai_promptDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a ai_promptDo) Delete(models ...*model.Ai_prompt) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *ai_promptDo) withDO(do gen.Dao) *ai_promptDo {
	a.DO = *do.(*gen.DO)
	return a
}
