// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Ai_chat_logs:    newAi_chat_logs(db, opts...),
		Ai_prompt:       newAi_prompt(db, opts...),
		Ai_session_logs: newAi_session_logs(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Ai_chat_logs    ai_chat_logs
	Ai_prompt       ai_prompt
	Ai_session_logs ai_session_logs
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Ai_chat_logs:    q.Ai_chat_logs.clone(db),
		Ai_prompt:       q.Ai_prompt.clone(db),
		Ai_session_logs: q.Ai_session_logs.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Ai_chat_logs:    q.Ai_chat_logs.replaceDB(db),
		Ai_prompt:       q.Ai_prompt.replaceDB(db),
		Ai_session_logs: q.Ai_session_logs.replaceDB(db),
	}
}

type queryCtx struct {
	Ai_chat_logs    *ai_chat_logsDo
	Ai_prompt       *ai_promptDo
	Ai_session_logs *ai_session_logsDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Ai_chat_logs:    q.Ai_chat_logs.WithContext(ctx),
		Ai_prompt:       q.Ai_prompt.WithContext(ctx),
		Ai_session_logs: q.Ai_session_logs.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
