// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_knowledge_base_gdb

import (
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/dal/db/dbif/urtyg_ai_agent_if/ai_knowledge_base_if"
	"github.com/freedqo/fmc-go-agents/internal/fmc-go-agents-server/model/dalm/dbm/urtyg_ai_agent/query"
	"gorm.io/gorm"
)

func New(gdb *gorm.DB, genQ *query.Query) ai_knowledge_base_if.If {
	return &Ai_knowledge_base_gdb{
		genIf:  newGenIF(gdb),
		selfIf: newSelfIF(gdb, genQ),
	}
}

type Ai_knowledge_base_gdb struct {
	genIf  ai_knowledge_base_if.GenIf
	selfIf ai_knowledge_base_if.SelfIf
}

func (c *Ai_knowledge_base_gdb) Gen() ai_knowledge_base_if.GenIf {
	return c.genIf
}

func (c *Ai_knowledge_base_gdb) Self() ai_knowledge_base_if.SelfIf {
	return c.selfIf
}
