// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/model/dalm/dbm"
)

// Ai_chat_logs_QueryReq 是用于查询 Ai_chat_logs 表的请求结构体
type Ai_chat_logs_QueryReq struct {
    // 消息内容
    Content *string `json:"Content" column:"content" form:"Content"`
    // 消息创建时间
    CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
    // 记录唯一id
    ID *string `json:"ID" column:"id" form:"ID"`
    // 消息顺序
    Order *string `json:"Order" column:"order" form:"Order"`
    // 消息角色
    Role *string `json:"Role" column:"role" form:"Role"`
    // 会话唯一标识
    SessionID *string `json:"SessionID" column:"session_id" form:"SessionID"`
    // 用户ID
    UserID *string `json:"UserID" column:"user_id" form:"UserID"`
    // 排序字段，例如 "字段名 asc" 或 "字段名 desc"
    OrderBy *string `json:"OrderBy" form:"OrderBy"`
    // 是否模糊查询
    IsLike bool `json:"IsLike" form:"IsLike"`
    // 分页信息
    Page *dbm.Page `json:"Page" form:"Page"`
}
