// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_prompt = "ai_prompt"

// Ai_prompt 用户提示词模板表
type Ai_prompt struct {
	ID          string     `gorm:"column:id;type:varchar(60);primaryKey;comment:模板唯一ID" json:"id"`                                                                                   // 模板唯一ID
	UserID      string     `gorm:"column:user_id;type:varchar(50);not null;uniqueIndex:uniq_user_type_active,priority:1;index:idx_user_id,priority:1;comment:创建用户ID" json:"user_id"` // 创建用户ID
	Type        string     `gorm:"column:type;type:varchar(30);not null;uniqueIndex:uniq_user_type_active,priority:2;index:idx_template_type,priority:1;comment:模板类型" json:"type"`   // 模板类型
	Name        string     `gorm:"column:name;type:varchar(100);not null;comment:模板名称" json:"name"`                                                                                  // 模板名称
	Description string     `gorm:"column:description;type:varchar(500);comment:模板描述" json:"description"`                                                                             // 模板描述
	Content     string     `gorm:"column:content;type:text;not null;comment:模板内容(md格式)" json:"content"`                                                                              // 模板内容(md格式)
	IsShared    bool       `gorm:"column:is_shared;type:tinyint(1);not null;index:idx_is_shared,priority:1;comment:是否分享(0-私有,1-公开)" json:"is_shared"`                                // 是否分享(0-私有,1-公开)
	SharedAt    time.Time  `gorm:"column:shared_at;type:timestamp;comment:分享时间" json:"shared_at"`                                                                                    // 分享时间
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                               // 更新时间
}

// TableName Ai_prompt's table name
func (*Ai_prompt) TableName() string {
	return TableNameAi_prompt
}
