// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/model/dalm/dbm"
)

// Ai_prompt_QueryReq 是用于查询 Ai_prompt 表的请求结构体
type Ai_prompt_QueryReq struct {
    // 模板内容(md格式)
    Content *string `json:"Content" column:"content" form:"Content"`
    // 创建时间
    CreatedAt *string `json:"CreatedAt" column:"created_at" form:"CreatedAt"`
    // 模板描述
    Description *string `json:"Description" column:"description" form:"Description"`
    // 模板唯一ID
    ID *string `json:"ID" column:"id" form:"ID"`
    // 是否分享(0-私有,1-公开)
    IsShared *string `json:"IsShared" column:"is_shared" form:"IsShared"`
    // 模板名称
    Name *string `json:"Name" column:"name" form:"Name"`
    // 分享时间
    SharedAt *string `json:"SharedAt" column:"shared_at" form:"SharedAt"`
    // 模板类型
    Type *string `json:"Type" column:"type" form:"Type"`
    // 更新时间
    UpdatedAt *string `json:"UpdatedAt" column:"updated_at" form:"UpdatedAt"`
    // 创建用户ID
    UserID *string `json:"UserID" column:"user_id" form:"UserID"`
    // 排序字段，例如 "字段名 asc" 或 "字段名 desc"
    OrderBy *string `json:"OrderBy" form:"OrderBy"`
    // 是否模糊查询
    IsLike bool `json:"IsLike" form:"IsLike"`
    // 分页信息
    Page *dbm.Page `json:"Page" form:"Page"`
}
