// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/freedqo/fmc-go-agent/internal/fmc-go-agent-server/model/dalm/dbm"
)

// Ai_session_logs_QueryReq 是用于查询 Ai_session_logs 表的请求结构体
type Ai_session_logs_QueryReq struct {
    // 会话记录id
    ID *string `json:"ID" column:"id" form:"ID"`
    // 最后时间
    LastAt *string `json:"LastAt" column:"last_at" form:"LastAt"`
    // 提示词模板id
    PromptID *string `json:"PromptID" column:"prompt_id" form:"PromptID"`
    // 用户id
    UserID *string `json:"UserID" column:"user_id" form:"UserID"`
    // 排序字段，例如 "字段名 asc" 或 "字段名 desc"
    OrderBy *string `json:"OrderBy" form:"OrderBy"`
    // 是否模糊查询
    IsLike bool `json:"IsLike" form:"IsLike"`
    // 分页信息
    Page *dbm.Page `json:"Page" form:"Page"`
}
