// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAi_session_logs = "ai_session_logs"

// Ai_session_logs mapped from table <ai_session_logs>
type Ai_session_logs struct {
	ID       string    `gorm:"column:id;type:varchar(255);primaryKey;comment:会话记录id" json:"id"`             // 会话记录id
	UserID   string    `gorm:"column:user_id;type:varchar(60);not null;comment:用户id" json:"user_id"`        // 用户id
	PromptID string    `gorm:"column:prompt_id;type:varchar(60);not null;comment:提示词模板id" json:"prompt_id"` // 提示词模板id
	LastAt   time.Time `gorm:"column:last_at;type:timestamp;comment:最后时间" json:"last_at"`                   // 最后时间
}

// TableName Ai_session_logs's table name
func (*Ai_session_logs) TableName() string {
	return TableNameAi_session_logs
}
