// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
    "gorm.io/gorm"
)

func GetModels() []interface{} {
    m := make([]interface{}, 0)
    v0 := Ai_chat_logs{}
    m = append(m, v0)
    v1 := Ai_prompt{}
    m = append(m, v1)
    v2 := Ai_session_logs{}
    m = append(m, v2)
    return m
}

func AutoMigrate(db *gorm.DB) error {
    if err := db.AutoMigrate(GetModels()...); err != nil {
        return err
    }
    return nil
}
